#!/bin/bash

echo "🔍 Vérification du statut - Show Room Pro"
echo "========================================="
echo ""

# Vérifier si lié à Railway
if [ -d ".railway" ]; then
    echo "✅ Projet lié à Railway"
else
    echo "⚠️  Projet non lié à Railway"
fi

echo ""
echo "📊 Essai de récupération du statut Railway..."
railway status 2>/dev/null || echo "❌ Impossible de récupérer le statut (normal si non lié au bon service)"

echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 CHECKLIST DE DÉPLOIEMENT"
echo ""
echo "Backend:"
echo "  [ ] Service déployé (🟢 sur Railway)"
echo "  [ ] Base de données migrée (yarn medusa db:migrate)"
echo "  [ ] Données seed insérées (yarn run seed)"
echo "  [ ] Admin créé (yarn medusa user...)"
echo "  [ ] API accessible (https://backend-xxx/health)"
echo ""
echo "Storefront:"
echo "  [ ] Service déployé (🟢 sur Railway)"
echo "  [ ] Clé publique configurée (NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY)"
echo "  [ ] Site accessible (https://storefront-xxx)"
echo "  [ ] Branding Show Room Pro visible"
echo ""
echo "Configuration:"
echo "  [ ] URLs CORS mises à jour dans Backend"
echo "  [ ] URL Backend mise à jour dans Storefront"
echo "  [ ] URL Storefront mise à jour dans Storefront"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "📝 PROCHAINES ÉTAPES RECOMMANDÉES:"
echo ""
echo "1. Si DB pas initialisée :"
echo "   → Railway.app → Backend → Terminal"
echo "   → Exécutez: yarn medusa db:migrate && yarn run seed"
echo ""
echo "2. Si pas de clé publique :"
echo "   → Railway.app → PostgreSQL → Connect → psql"
echo "   → SELECT token FROM api_key WHERE type = 'publishable';"
echo ""
echo "3. Mettre la clé dans Storefront :"
echo "   → Railway.app → Storefront → Variables"
echo "   → NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY = pk_..."
echo ""
echo "4. Vérifier les URLs :"
echo "   → Notez vos URLs Railway"
echo "   → Mettez à jour CORS et URLs dans les variables"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
