#!/bin/bash
set -e

echo "🗄️  Initialisation de la base de données Railway"
echo "================================================"
echo ""

echo "📝 Instructions :"
echo "1. Allez sur Railway → Projet showroompro"
echo "2. Cliquez sur le service Backend"
echo "3. Onglet 'Shell' ou 'Terminal'"
echo "4. Exécutez ces commandes UNE PAR UNE :"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "# 1. Créer la base de données"
echo "yarn medusa db:create"
echo ""
echo "# 2. Exécuter les migrations"
echo "yarn medusa db:migrate"
echo ""
echo "# 3. Seed les données initiales"
echo "yarn run seed"
echo ""
echo "# 4. Créer l'admin"
echo "yarn medusa user -e admin@showroompro.com -p VotreMotDePasse123! -i admin"
echo ""
echo "# 5. Récupérer la clé publique"
echo "yarn medusa exec 'SELECT token FROM api_key WHERE type = '\''publishable'\'';'"
echo ""
echo "═══════════════════════════════════════════════"
echo ""
echo "📋 OU utilisez le shell PostgreSQL pour la clé :"
echo ""
echo "Dans Railway → PostgreSQL → Connect → Shell:"
echo "SELECT token FROM api_key WHERE type = 'publishable';"
echo ""
echo "💾 COPIEZ la clé qui commence par pk_..."
echo ""
echo "📝 Puis mettez-la dans Storefront → Variables:"
echo "NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=pk_votre_cle_ici"
echo ""
