[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]

[deploy]
startCommand = "echo 'Use service-specific start commands'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
